### PR TITLE
answers for lesson 1

### PR DESCRIPTION
**Pull request by mykyta-kovalenko**

### CODE REVIEW

**Review by taiwo2 — COMMENTED** [review]
Currently, I'm unable to run your answer for 08-os-module.js and prompter.js. Additionally I have not seen how you answer this question. Could you please explain or work me through on how you answer this questions?
Please answer the below prompts in your assignment submission:

What’s your rule of thumb for when to ask for help?
When is an instance where you wish you would have asked for help sooner?
What information have you found crucial to include in your questions so that mentors or peers can help answer your questions quicker?

**Comment by mykyta-kovalenko** [comment]
> Currently, I'm unable to run your answer for 08-os-module.js and prompter.js. Additionally I have not seen how you answer this question. Could you please explain or work me through on how you answer this questions? Please answer the below prompts in your assignment submission:
> 
> What’s your rule of thumb for when to ask for help? When is an instance where you wish you would have asked for help sooner? What information have you found crucial to include in your questions so that mentors or peers can help answer your questions quicker?

Taiwo, did you clone my repository or copy-paste code into your environment?
The thing is, I used ES6 imports instead of old CommonJS modules.
To turn it on, add `"type": "module"` to your `package.json` file.

My answers to these questions are provided in the submission form.

**Comment by mykyta-kovalenko** [comment]
@taiwo2 pushed a small fix for 08, prompter should work as well.
Знімок екрана 2024-06-18 о 11 57 26 дп

**Review by taiwo2 — COMMENTED** [review]
Well Done and Good explanation. Keep it up! 💯

**Pull request merged**
